version: '3'

networks:
    network-eureka:

services:
    eureka-server:
        container_name:
            eureka-container
        image: springcloud/eureka
        ports:
            - "8761:8761"
        networks:
            - network-eureka
    order:
        container_name:
            order
        build: './order'
        ports:
            - "8082:8082"
        depends_on:
            - eureka-server
        environment:
            - SERVER_HTTP=http://eureka-server:8761/eureka
        networks:
            - network-eureka
    catalog:
        container_name:
            catalog
        build: './catalog'
        ports:
            - "8083:8083"
        depends_on:
            - eureka-server
        environment:
            - SERVER_HTTP=http://eureka-server:8761/eureka
        networks:
            - network-eureka
    account:
        container_name:
            account
        build: './account'
        ports:
            - "8084:8084"
        depends_on:
            - eureka-server
        environment:
            - SERVER_HTTP=http://eureka-server:8761/eureka
        networks:
            - network-eureka
#    frontend:
#        container_name:
#            frontend
#        build: './frontend'
#        ports:
#            - "8080:8080"
#        depends_on:
#            - eureka-server
#        environment:
#            - ACCOUNT_ADR=http://account:8761/eureka
#            - ORDER_ADR=http://order:8761/eureka
#            - CATALOG_ADR=http://catalog:8761/eureka
#        networks:
#            - network-eureka
